version: '3.5'
volumes:
  db_data:

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080

  mysql:
    image: mysql:5.6
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;'
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: demodb
    volumes:
      - db_data:/var/lib/mysql

