# MySQL config -  https://spring.io/guides/gs/accessing-data-mysql/#initial
spring.datasource:
  url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/demodb?createDatabaseIfNotExist=true
  username: root
  password: example

## Hibernate Properties
# https://docs.jboss.org/hibernate/orm/5.2/userguide/html_single/Hibernate_User_Guide.html#configurations-hbmddl
spring.jpa:
  hibernate.ddl-auto: none 
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

## Hibernate Logging
# logging.level.org.hibernate.SQL: DEBUG

# liquibase
spring.liquibase.change-log: classpath:bbdd/mysql-changelog.yaml
logging.level.liquibase: INFO

server:
  port: 8082

